x-app-volumes: &app-volumes
  - ./html:/var/www/html
  - ./config/php.custom.ini:/usr/local/etc/php/conf.d/custom.ini

services:
  base:
    image: atropim-base:latest
    build:
      context: .
      dockerfile: docker/base.Dockerfile
    deploy:
      mode: replicated
      replicas: 0

  db:
    image: postgres:16-alpine
    container_name: ${PROJECT_NAME}-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/postgresql/data
    command: postgres -c shared_buffers=${DB_MEMORY_LIMIT} -c work_mem=16MB

  app:
    user: www-data
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    container_name: ${PROJECT_NAME}-app
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: 5432
      PHP_OPCACHE_ENABLE: 1
      PHP_OPCACHE_JIT: 1255
      PHP_OPCACHE_JIT_BUFFER_SIZE: 100M
    volumes: *app-volumes
    healthcheck:
      test: ["CMD", "test", "-f", "/var/www/html/vendor/autoload.php"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s
    depends_on:
      db:
        condition: service_started
      base:
        condition: service_completed_successfully

  cron:
    build:
      context: .
      dockerfile: docker/cron.Dockerfile
    container_name: ${PROJECT_NAME}-cron
    restart: always
    volumes: *app-volumes
    depends_on:
      app:
        condition: service_healthy 

  web:
    image: nginx:mainline-alpine
    container_name: ${PROJECT_NAME}-web
    restart: always
    volumes:
      - ./html/public:/var/www/html/public
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:

networks:
  default:
    driver: bridge
    name: ${PROJECT_NAME}_default
